theme = "ayu_mirage"

[editor]
  line-number = "relative"
  mouse = true
  cursorline = true
  color-modes = true
  true-color = true
  rulers = [80, 100, 120]
  completion-trigger-len = 1
  bufferline = "always"
  scrolloff = 10
  idle-timeout = 8

[editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "underline"

[editor.file-picker]
  hidden = false

[editor.lsp]
  display-messages = true

[editor.indent-guides]
  render = true
  #character = "╎"

[editor.whitespace]
  render = "none"

[editor.whitespace.characters]
  space = "."
  nbsp = "⍽"
  tab = "→"
  newline = "⏎"
  tabpad = "."

[keys.normal]
  X = "extend_line_above"
  C-p = ["move_line_up", "scroll_up"]
  C-n = ["move_line_down", "scroll_down"]
  esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal.space]
  c = ":buffer-close"
  C = ":buffer-close-others"
  q = ":quit"
  w = ":write"
