theme = "sonokai_andromeda"

[editor]
  line-number = "relative"
  mouse = true
  cursorline = true
  color-modes = true
  rulers = [80]
  auto-info = false
  bufferline = "multiple"
  scrolloff = 10

[editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "underline"

[editor.file-picker]
  hidden = false

[editor.lsp]
  display-messages = true

[editor.auto-pairs]
  '"' = '"'
  '(' = ')'
  '{' = '}'
  '`' = '`'
  '[' = ']'
  "'" = "'"
  
[editor.indent-guides]
  render = true
  #character = "╎"

[editor.whitespace]
  render = "none"

[editor.whitespace.characters]
  space = "."
  nbsp = "⍽"
  tab = "→"
  newline = "⏎"
  tabpad = "."

[keys.normal]
  space = { c = ":buffer-close", C = ":buffer-close-others" }
