theme = "ayu_mirage"

[editor]
  line-number = "relative"
  mouse = true
  cursorline = true
  color-modes = true
  rulers = [80, 100, 120]
  completion-trigger-len = 1
  bufferline = "multiple"
  scrolloff = 10

[editor.cursor-shape]
  insert = "bar"
  normal = "block"
  select = "underline"

[editor.file-picker]
  hidden = false

[editor.lsp]
  display-messages = true

[editor.indent-guides]
  render = true
  #character = "╎"

[editor.whitespace]
  render = "none"

[editor.whitespace.characters]
  space = "."
  nbsp = "⍽"
  tab = "→"
  newline = "⏎"
  tabpad = "."

[keys.normal]
  X = "extend_line_above"

[keys.normal.space]
  c = ":buffer-close"
  C = ":buffer-close-others"
  q = ":quit"
  w = ":write"
