[[language]]
  name = "cpp"
  scope = "source.cpp"
  injection-regex = "cpp"
  file-types = ["cc", "hh", "c++", "cpp", "hpp", "h", "ipp", "tpp", "cxx", "hxx", "ixx", "txx", "ino", "C", "H", "cu", "cuh"]
  roots = []
  comment-token = "//"
  language-servers = [ "clangd" ]
  indent = { tab-width = 4, unit = "\t" }
